name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# TODO APP VERSION
version: 2.0.0+6

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  app_links: ^6.1.4
  audioplayers: ^6.1.1
  awesome_dialog: ^3.2.1
  awesome_notifications: ^0.9.3+1
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  # country_code_picker: ^3.0.0
  device_info_plus: ^10.1.1
  dotted_border: ^2.1.0
  external_path: ^2.0.1
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_paystack: ^1.0.7
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_api_headers: ^4.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^6.1.0
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  open_filex: ^4.4.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  paytm_allinonesdk: ^1.2.6
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^5.0.0
  provider: ^6.1.2
  quickalert: ^1.1.0
  quill_html_editor: ^2.2.8
  razorpay_flutter: ^1.3.3
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.1
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.0
  version: ^3.0.2
  vibration: ^2.0.1

dependency_overrides:
  http: ^1.2.0
  intl: ^0.19.0
  google_maps_flutter_ios: 2.5.2
  stripe_android: ^10.2.1
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master

flutter:
  uses-material-design: true

  assets:
    - assets/en.json
    - assets/svg/
    - assets/images/
    - assets/mapTheme/
    - assets/sounds/
